#!/usr/bin/env python3
"""Generate an A-Frame HTML scene from resolved scene JSON.

Usage:
    python generators/generate_aframe.py < output/scene_resolved.json

Reads resolved scene JSON from stdin and writes an immersive A-Frame
HTML file to webXR/index.html. Copies referenced .glb assets into webXR/.
Copies scene index + scene files into webXR/scenes/ for multi-scene menu.
"""

import sys
import json
import os
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
WEBXR_DIR = os.path.join(PROJECT_ROOT, "webXR")
ASSET_MAP_PATH = os.path.join(SCRIPT_DIR, "asset_map.json")
SCENES_DIR = os.path.join(PROJECT_ROOT, "output", "scenes")

DEFAULT_PANORAMA = "punk_house.png"
DEFAULT_PANORAMA_SOURCE = os.path.join(
    PROJECT_ROOT, "assets", "images", "360", "Mexican Punk House Surf_pano.png"
)
# Minimum Y position so models float above the floor for full-body view
MIN_MODEL_Y = 0.5

AFRAME_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>XR Scene — Generated by Gemini Agent</title>
  <script src="https://aframe.io/releases/1.7.0/aframe.min.js"></script>
  <style>
    #scene-menu {{
      position: fixed;
      top: 16px;
      right: 16px;
      z-index: 9999;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    }}
    #menu-toggle {{
      background: rgba(0,0,0,0.7);
      color: #fff;
      border: 1px solid rgba(255,255,255,0.3);
      padding: 8px 16px;
      border-radius: 8px;
      cursor: pointer;
      font-size: 14px;
    }}
    #menu-toggle:hover {{ background: rgba(0,0,0,0.85); }}
    #scene-list {{
      display: none;
      margin-top: 8px;
      background: rgba(0,0,0,0.8);
      border: 1px solid rgba(255,255,255,0.2);
      border-radius: 8px;
      padding: 8px 0;
      min-width: 200px;
      max-height: 300px;
      overflow-y: auto;
    }}
    .scene-item {{
      display: block;
      padding: 8px 16px;
      color: #ccc;
      text-decoration: none;
      font-size: 13px;
      cursor: pointer;
      border: none;
      background: none;
      width: 100%;
      text-align: left;
    }}
    .scene-item:hover {{ background: rgba(255,255,255,0.1); color: #fff; }}
    .scene-item.active {{ color: #FFD6E0; font-weight: bold; }}
  </style>
</head>
<body>
  <!-- Scene menu -->
  <div id="scene-menu">
    <button id="menu-toggle">Scenes</button>
    <div id="scene-list">
{menu_items}
    </div>
  </div>

  <a-scene>
    <!-- Assets (must come first for preloading) -->
    <a-assets>
{sky_asset}
{asset_tags}
    </a-assets>

    <!-- 360 panorama sphere — pastel pink fallback if no image loads -->
    <a-sky {sky_attr} color="#FFD6E0"></a-sky>

    <!-- Lighting — strong, even illumination for model visibility -->
    <a-entity light="type: ambient; color: #fff; intensity: 2.0"></a-entity>
    <a-entity light="type: directional; color: #fff; intensity: 2.5" position="-2 4 2"></a-entity>
    <a-entity light="type: directional; color: #ffd6e0; intensity: 1.2" position="2 3 -1"></a-entity>
    <a-entity light="type: hemisphere; color: #fff; groundColor: #ffd6e0; intensity: 1.5"></a-entity>

    <!-- Generated entities container -->
    <a-entity id="scene-entities">
{entities}
    </a-entity>

    <!-- Camera rig — standing height, facing models -->
    <a-entity id="rig" position="0 0 4">
      <a-camera position="0 1.6 0" look-controls wasd-controls></a-camera>
    </a-entity>
  </a-scene>

  <script>
    // Scene menu toggle
    const menuToggle = document.getElementById('menu-toggle');
    const sceneList = document.getElementById('scene-list');
    if (menuToggle && sceneList) {{
      menuToggle.addEventListener('click', () => {{
        sceneList.style.display = sceneList.style.display === 'none' ? 'block' : 'none';
      }});
      // Press M to toggle menu
      document.addEventListener('keydown', (e) => {{
        if (e.key === 'm' || e.key === 'M') {{
          sceneList.style.display = sceneList.style.display === 'none' ? 'block' : 'none';
        }}
      }});
    }}

    // Scene switching
    async function loadScene(sceneId) {{
      try {{
        const resp = await fetch('scenes/' + sceneId + '.json');
        if (!resp.ok) return;
        const scene = await resp.json();

        // Remove existing models
        const container = document.getElementById('scene-entities');
        while (container.firstChild) container.removeChild(container.firstChild);

        // Add new models
        const chars = scene.characters || [];
        for (const char of chars) {{
          const el = document.createElement('a-gltf-model');
          const asset = char.asset || 'character';
          el.setAttribute('src', asset + '.glb');
          const pos = char.position || [0, 1, -3];
          const y = pos[1] < {min_y} ? {min_y} : pos[1];
          el.setAttribute('position', pos[0] + ' ' + y + ' ' + pos[2]);
          container.appendChild(el);
        }}

        // Update active menu item
        document.querySelectorAll('.scene-item').forEach(item => {{
          item.classList.toggle('active', item.dataset.scene === sceneId);
        }});
      }} catch (err) {{
        console.error('Failed to load scene:', err);
      }}
    }}

    document.querySelectorAll('.scene-item').forEach(item => {{
      item.addEventListener('click', (e) => {{
        e.preventDefault();
        loadScene(item.dataset.scene);
      }});
    }});
  </script>
</body>
</html>
"""


def find_glb_source(logical_name: str) -> str | None:
    """Find the .glb source file for a logical asset name."""
    with open(ASSET_MAP_PATH) as f:
        asset_map = json.load(f)

    if logical_name in asset_map and "webxr" in asset_map[logical_name]:
        path = os.path.join(PROJECT_ROOT, asset_map[logical_name]["webxr"])
        if os.path.exists(path):
            return path

    # Fallback: search assets/models/<name>/ for any .glb
    model_dir = os.path.join(PROJECT_ROOT, "assets", "models", logical_name)
    if os.path.isdir(model_dir):
        for root, _, files in os.walk(model_dir):
            for f in files:
                if f.endswith(".glb"):
                    return os.path.join(root, f)
    return None


def add_character(char: dict, entity_lines, asset_tag_lines, glb_files_to_copy, seen_assets):
    """Process a single character dict into A-Frame entities and assets."""
    logical_name = char.get("asset", "character")
    glb_filename = f"{logical_name}.glb"
    pos = list(char.get("position", [0, 1, -3]))
    # Ensure models are raised above floor for full-body visibility
    if len(pos) >= 2 and pos[1] < MIN_MODEL_Y:
        pos[1] = MIN_MODEL_Y
    pos_str = f"{pos[0]} {pos[1]} {pos[2]}"
    char_type = char.get("type", logical_name)

    asset_id = f"model-{logical_name}"
    entity_lines.append(
        f'    <a-gltf-model src="#{asset_id}" position="{pos_str}" '
        f'title="{char_type}"></a-gltf-model>'
    )

    # Only add asset tag and copy file once per logical name
    if logical_name not in seen_assets:
        seen_assets.add(logical_name)
        asset_tag_lines.append(
            f'      <a-asset-item id="{asset_id}" src="{glb_filename}"></a-asset-item>'
        )
        source = find_glb_source(logical_name)
        if source:
            glb_files_to_copy.append((source, glb_filename))
        else:
            print(f"Warning: no .glb found for '{logical_name}'", file=sys.stderr)


def resolve_panorama(scene: dict) -> tuple[str, str | None]:
    """Determine the sky source and optional file to copy."""
    bg = scene.get("background")
    if bg and bg.get("exists"):
        bg_asset = bg.get("asset", "")
        for candidate in [bg_asset, f"{bg_asset}.png", f"{bg_asset}.jpg"]:
            path = os.path.join(PROJECT_ROOT, "assets", "backgrounds", candidate)
            if os.path.exists(path):
                filename = os.path.basename(path)
                return filename, path

    if os.path.exists(DEFAULT_PANORAMA_SOURCE):
        return DEFAULT_PANORAMA, DEFAULT_PANORAMA_SOURCE

    return None, None


def build_menu_items() -> str:
    """Build HTML menu items from the scene index."""
    index_path = os.path.join(SCENES_DIR, "index.json")
    if not os.path.exists(index_path):
        return '      <span class="scene-item" style="color:#888;">No scenes saved yet</span>'

    with open(index_path) as f:
        index = json.load(f)

    if not index.get("scenes"):
        return '      <span class="scene-item" style="color:#888;">No scenes saved yet</span>'

    lines = []
    default_id = index.get("default")
    for s in index["scenes"]:
        active = " active" if s["id"] == default_id else ""
        lines.append(
            f'      <button class="scene-item{active}" data-scene="{s["id"]}">'
            f'{s["label"]}</button>'
        )
    return "\n".join(lines)


def copy_scenes_to_webxr():
    """Copy scene index + scene files into webXR/scenes/ for browser access."""
    webxr_scenes = os.path.join(WEBXR_DIR, "scenes")
    os.makedirs(webxr_scenes, exist_ok=True)

    if not os.path.isdir(SCENES_DIR):
        return

    for f in os.listdir(SCENES_DIR):
        if f.endswith(".json"):
            src = os.path.join(SCENES_DIR, f)
            dst = os.path.join(webxr_scenes, f)
            shutil.copy2(src, dst)


def generate(scene: dict) -> tuple[str, list]:
    """Generate A-Frame HTML from resolved scene JSON."""
    entity_lines = []
    asset_tag_lines = []
    glb_files_to_copy = []
    seen_assets = set()
    extra_files_to_copy = []

    if "characters" in scene:
        for char in scene["characters"]:
            add_character(char, entity_lines, asset_tag_lines, glb_files_to_copy, seen_assets)
    elif scene.get("action") == "add_character" and "character" in scene:
        add_character(scene["character"], entity_lines, asset_tag_lines, glb_files_to_copy, seen_assets)

    sky_src, pano_source = resolve_panorama(scene)
    if pano_source and sky_src:
        extra_files_to_copy.append((pano_source, sky_src))

    entities = "\n".join(entity_lines) if entity_lines else "      <!-- No entities -->"
    asset_tags = "\n".join(asset_tag_lines) if asset_tag_lines else ""
    menu_items = build_menu_items()

    if sky_src:
        sky_asset = f'      <img id="sky-texture" src="{sky_src}" crossorigin="anonymous">'
        sky_attr = 'src="#sky-texture"'
    else:
        sky_asset = "      <!-- No panorama image -->"
        sky_attr = ""

    html = AFRAME_TEMPLATE.format(
        entities=entities,
        asset_tags=asset_tags,
        sky_asset=sky_asset,
        sky_attr=sky_attr,
        menu_items=menu_items,
        min_y=MIN_MODEL_Y,
    )

    return html, glb_files_to_copy + extra_files_to_copy


def main():
    scene = json.load(sys.stdin)

    os.makedirs(WEBXR_DIR, exist_ok=True)

    html, files_to_copy = generate(scene)

    output_path = os.path.join(WEBXR_DIR, "index.html")
    with open(output_path, "w") as f:
        f.write(html)
    print(f"Wrote {output_path}", file=sys.stderr)

    for source, dest_name in files_to_copy:
        dest = os.path.join(WEBXR_DIR, dest_name)
        shutil.copy2(source, dest)
        print(f"Copied {source} → {dest}", file=sys.stderr)

    # Copy scene files for multi-scene menu
    copy_scenes_to_webxr()


if __name__ == "__main__":
    main()
