//
//  SceneLoader.swift
//  VercelDeepmindHack
//
//  Loads scene JSON generated by the Gemini agent and creates RealityKit entities.
//

import Foundation
import RealityKit

// MARK: - JSON Model (matches Gemini agent output)

struct SceneDescription: Codable {
    let characters: [CharacterInstruction]
}

struct CharacterInstruction: Codable {
    let type: String
    let asset: String
    let resolvedAsset: String?
    let position: [Float]

    enum CodingKeys: String, CodingKey {
        case type, asset, position
        case resolvedAsset = "resolved_asset"
    }

    var simdPosition: SIMD3<Float> {
        SIMD3<Float>(
            position.count > 0 ? position[0] : 0,
            position.count > 1 ? position[1] : 0,
            position.count > 2 ? position[2] : 0
        )
    }

    /// The .usdz filename to load (without extension). Uses resolved_asset if available, falls back to asset.
    var modelName: String {
        let filename = resolvedAsset ?? asset
        // Strip .usdz extension if present
        if filename.hasSuffix(".usdz") {
            return String(filename.dropLast(5))
        }
        return filename
    }
}

// MARK: - Scene Loader

@MainActor
class SceneLoader {

    /// Load a scene JSON file from the app bundle and return entities to add.
    static func loadFromBundle(filename: String = "scene") async throws -> [Entity] {
        guard let url = Bundle.main.url(forResource: filename, withExtension: "json") else {
            print("SceneLoader: \(filename).json not found in bundle")
            return []
        }
        let data = try Data(contentsOf: url)
        return try await buildEntities(from: data)
    }

    /// Parse JSON data and build RealityKit entities.
    static func buildEntities(from data: Data) async throws -> [Entity] {
        let scene = try JSONDecoder().decode(SceneDescription.self, from: data)
        var entities: [Entity] = []

        for character in scene.characters {
            let entity = try await createCharacterEntity(character)
            entities.append(entity)
        }

        return entities
    }

    /// Create a RealityKit entity from a character instruction.
    /// Tries to load a .usdz model matching the asset name; falls back to a placeholder sphere.
    private static func createCharacterEntity(_ character: CharacterInstruction) async throws -> Entity {
        let entity: Entity

        // Try loading a .usdz model from the bundle using resolved name
        let name = character.modelName
        if let modelURL = Bundle.main.url(forResource: name, withExtension: "usdz") {
            entity = try await Entity(contentsOf: modelURL)
        } else {
            // Fallback: colored sphere as placeholder
            print("SceneLoader: \(name).usdz not found, using placeholder sphere")
            let mesh = MeshResource.generateSphere(radius: 0.2)
            let material = SimpleMaterial(color: .purple, isMetallic: false)
            entity = ModelEntity(mesh: mesh, materials: [material])
        }

        entity.name = character.asset
        entity.position = character.simdPosition

        return entity
    }
}
